### ISSUE TITLE
Another Noob Question

### ISSUE THREAD

**Issue by thorian93** [patrickbr/piwik-LoginFailLog#5]
Hi Patrick,
I am feeling very stupid right now, so excuse the stupid question: Where is the output of your plugin logged?! I have a running Matomo instance and I have a running Fail2Ban instance. I understand the filters basically and I got something like this to work for Nextcloud. The only thing I am apparently missing is where to point my jail config.
Can you help here?

Thanks in advance!
Thorian93

**Comment by patrickbr** [comment]
Maybe [this](https://matomo.org/faq/troubleshooting/faq_115/) will help? Basically, you have to enable file logging and specifiy an output file :)

**Comment by thorian93** [comment]
Now I figured it out, thanks! And thanks for lightning fast answer! 👍 
Maybe you want to add that hint to your documentation? 😉

**Comment by patrickbr** [comment]
Good idea! It is now included in the README.
